name: Reusable workflow for building a Docker image and pushing to ECR

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      workdir:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
     

jobs:
  build_push:
    runs-on: self-hosted
    environment: ${{inputs.environment}}
    container:
      image: gcr.io/kaniko-project/executor:v1.9.1-debug
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/my-github-actions-push-glue
          aws-region: ${{vars.AWS_REGION}}
          mask-aws-account-id: true
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'
      - name: Build and push image
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
          /kaniko/executor \
            --context "${BUILD_DIR}" \
            --dockerfile "${BUILD_DIR}/Dockerfile" \
            --destination "${REGISTRY}/${REPO_NAME}:${{ github.sha }}" \
            --destination "${REGISTRY}/${REPO_NAME}:latest" \
            --cleanup \
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO_NAME: ${{vars.PROJECT_NAME}}-${{inputs.repo_name}}
          BUILD_DIR: ${{inputs.workdir}}