name: Reusable workflow for deploying the ECS backend static files

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string  
    secrets:
      AWS_ACCOUNT_ID:
        required: true
       
jobs:
  collect_static_backend:
    runs-on: ubuntu-latest
    container:
      image: python:3.10
    env:
      STATIC_ROOT: "static/"
      SECRET_KEY: "DUMMYSECRETKEYVALUE"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies pip
        run: pip install --no-cache-dir --upgrade pip pipenv
      - name: Install dep pipenv
        run: pipenv install --system --dev --deploy
      - name: Collect static
        run: python manage.py collectstatic --noinput --clear
      - name: Upload static files artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.environment}}-static
          path: static/