name: Reusable workflow for building and deploying front-end

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      runner:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true
     
jobs:
  build_static:
    runs-on: ${{inputs.runner}}
    container:
      image: node:17.4.0
    defaults:
      run:
        shell: bash
    environment: ${{inputs.environment}}
    env:
      CI: false
      REACT_APP_NODE_ENV: ${{vars.REACT_APP_NODE_ENV}}
      REACT_APP_SERVER_ENDPOINT: "${{vars.ENV_URL}}/api/v1/"
      REACT_APP_ENTRA_TENANT: "${{vars.REACT_APP_ENTRA_TENANT}}"
      REACT_APP_EMAIL_CONTACT: "${{vars.REACT_APP_EMAIL_CONTACT}}"
      REACT_APP_MSAL_REDIRECT_URI: "${{vars.ENV_URL}}/overview"
      REACT_APP_MSAL_AUTHORITY: ${{vars.REACT_APP_MSAL_AUTHORITY}}
      REACT_APP_MSAL_CLIENT_ID: ${{vars.REACT_APP_MSAL_CLIENT_ID}}
      REACT_APP_MSAL_SCOPES: ${{vars.REACT_APP_MSAL_SCOPES}}
      REACT_APP_GTM_ID: ${{vars.REACT_APP_GTM_ID}}
      REACT_APP_ENV_HEADER_NAME: ${{vars.REACT_APP_ENV_HEADER_NAME}}
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build static files
        run: |
          npm install
          npm run build
      - name: Check build success
        run: |
          ERR_CODE=$(ls build/ | grep -c "index.html") || true
          if [ $ERR_CODE -eq 0 ];
          then
            echo "Can not find index.html in build result" && exit 1;
          else
            echo "Building static files has been finished!";
          fi;
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{inputs.environment}}-static
          path: static/
