name: Reusable workflow for deploying the ECS backend static files

on:
  workflow_call:
    inputs:
      resource_type:
        required: true
        type: string  
      tag_filters:
        required: true
        type: string  

jobs:
  build_push:
    runs-on: ubuntu-latest
    outputs:
      resource_id: ${{steps.resource.outputs.ID}}
    steps:
      - name: Get bucket name via tags
        id: resource
        run: |
          echo "ID=$(aws resourcegroupstaggingapi get-resources \
            ${{inputs.tag_filters}} \
            --resource-type-filters '${{inputs.resource_type}}' \
            --region ${{secrets.AWS_REGION}} \
            --query 'ResourceTagMappingList[0].ResourceARN' \
            --output text )" \
            >> "$GITHUB_OUTPUT"
