name: Reusable workflow for copying glue scripts 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      role_name:
        required: true
        type: string
      identifier:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  upload_to_s3:
    name: 'Upload Glue scripts'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.PROJECT_NAME}}-${{inputs.identifier}}-${{inputs.environment}}-my-github-actions-${{inputs.role_name}}
          aws-region: ${{vars.AWS_REGION}}
          mask-aws-account-id: true
      - name: Get bucket ARN via tags
        uses: finddx/seq-treat-tbkb-github-actions/get-aws-resource-by-tag@getresv1
        id: bucket
        with:
          tag_filters: "--tag-filters Key=Usage,Values=glue-scripts Key=Environment,Values=${{inputs.environment}}"
          resource_type: "s3:bucket"
          aws_region: ${{vars.AWS_REGION}}
      - run: |
          bucket_name=$(echo ${BUCKET_FULL_ARN} | sed "s/.*://")
          cd ./cfn/glue-jobs/
          zip -r9 ETL_tools.zip biosql_gene_views.py variant_annotation_categorization.py phenotypic_data_views.py
          aws s3 cp ./  s3://${bucket_name}/glue-jobs/ --recursive
        env: 
          BUCKET_FULL_ARN: ${{steps.bucket.outputs.resource_id}}
