name: Reusable workflow for copying glue scripts 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  upload_to_s3:
    name: 'Upload Glue scripts'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/my-github-actions-push-glue
          aws-region: ${{vars.AWS_REGION}}
          mask-aws-account-id: true
      - run: aws s3 cp cfn/glue-jobs s3://${PROJECT_NAME}-main-${ENV_NAME}-glue-scripts/glue-jobs/ --recursive
        env:
          ENV_NAME: ${{vars.ENV_NAME}}
          PROJECT_NAME: ${{vars.PROJECT_NAME}}
