name: Reusable workflow for copying glue scripts 

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

jobs:
  upload_to_s3:
    name: 'Upload Glue scripts'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.PROJECT_NAME}}-main-${{inputs.environment}}-my-github-actions-push-glue
          aws-region: ${{vars.AWS_REGION}}
          mask-aws-account-id: true
      - run: |
          cd ./cfn/glue-jobs/
          zip -r9 ETL_tools.zip biosql_gene_views.py variant_annotation_categorization.py phenotypic_data_views.py
          aws s3 cp ./  s3://${{vars.PROJECT_NAME}}-main-${{inputs.environment}}-glue-scripts/glue-jobs/ --recursive