name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true

env:
  TF_VAR_project_name: ${{vars.PROJECT_NAME}}
  TF_VAR_environment: ${{vars.ENV_NAME}}
  TF_VAR_aws_region: ${{vars.AWS_REGION}}
  TF_VAR_no_reply_email: ${{vars.NO_REPLY}}
  TF_VAR_cf_domain: ${{vars.CF_DOMAIN}}
  TF_VAR_gh_action_roles: ${{vars.CICD_ROLES}}
  TF_VAR_chatbot_notifs_implementation: ${{vars.CHATBOT_NOTIFS}}
  TF_VAR_github_org_name: ${{github.repository_owner}}
  TF_VAR_github_repo_prefix: ${{vars.REPO_PREFIX}}

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        working-directory:  devops/envs/${{inputs.environment}}/
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Assuming the IAM role from AWS with admin rights
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
            role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.PROJECT_NAME}}-main-${{vars.ENV_NAME}}-my-github-actions-terraform
            aws-region: ${{vars.AWS_REGION}}
            mask-aws-account-id: true
  
    - name: Hashicorp Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.5"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true

    # Using a GitHub Personal Access Token (PAT) needed to read the terrafom module repository
    # Edit: removed the use of PAT as we have open sourced terraform modules
    - name: Terraform Init
      id: init
      run: |
        terraform init -input=false

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color
