name: Terraform

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      AWS_ACCOUNT_ID:
        required: true


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    defaults:
      run:
        working-directory:  devops/envs/${{inputs.environment}}/
  
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
            role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/${{vars.TF_VAR_PROJECT_NAME}}-main-${{vars.TF_VAR_ENV_NAME}}-my-github-actions-terraform
            aws-region: ${{vars.TF_VAR_AWS_REGION}}
            mask-aws-account-id: true
  
    - name: Hashicorp Setup
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.9.5"

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check
      continue-on-error: true
    
    - name: Terraform Init
      id: init
      run: |
        echo "machine github.com login x password ${MY_GH_TOKEN}" > ~/.netrc
        git config --global url."https://github.com/".insteadOf "git://github.com/"
        git config --global advice.detachedHead false
        terraform init -input=false
      env:
        MY_GH_TOKEN: ${{secrets.PAT_FINE_GRAINED}}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
    
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -no-color
      continue-on-error: true

